CREATE DATABASE banco;
CREATE SCHEMA sch_solucoes;
CREATE TABLE sch_solucoes.tb_historico (
		chcd_franquia CHARACTER(3) NULL,
		incd_empcod INTEGER NULL,
		binu_cpfatendente BIGINT NULL,
		dtdt_atendimento DATE NULL,
		vcds_tipo CHARACTER VARYING(100) NULL,
		vcds_assunto CHARACTER VARYING(300) NULL,
		vctx_mensagem CHARACTER VARYING(8000) NULL,
		inid_atendimentoconnect INTEGER NULL
);

CREATE TABLE sch_solucoes.tb_rco_a (
	franquia CHARACTER(3) NULL,
	codigo INTEGER NULL,
	nome_fantasia CHARACTER VARYING(1000) NULL,
	cpf_cnpj BIGINT NULL,
	data_inclusao DATE NULL,
	valor NUMERIC NULL,
	incserasa CHARACTER(3) NULL,
	datadeb DATE NULL,
	id INTEGER NULL,
	contrato TEXT NULL
);

CREATE TABLE sch_solucoes.tb_rco_b (
	franquia CHARACTER(3) NULL,
	codigo INTEGER NULL,
	nome_fantasia CHARACTER VARYING(1000) NULL,
	cpf_cnpj BIGINT NULL,
	data_inclusao DATE NULL,
	data_baixa DATE NULL,
	valor NUMERIC NULL,
	serasa CHARACTER(3) NULL,
	motivo_cancelamento CHARACTER VARYING(5) NULL,
	id INTEGER NULL,
	id_can CHARACTER VARYING(20) NULL,
	contrato TEXT NULL
);

CREATE TABLE sch_solucoes.tb_cadastro (
	frnCod CHARACTER(3) NULL,
	empCod INTEGER NULL,
	empNom CHARACTER VARYING(1000) NULL,
	empFil DATE NULL,
	empDatCan DATE NULL,
	empTel CHARACTER VARYING(20) NULL,
	empFax CHARACTER VARYING(20) NULL,
	empEma CHARACTER VARYING(100) NULL,
	tipCod CHARACTER VARYING(5) NULL,
	RD CHARACTER VARYING(100) NULL NULL,
	Situacao_Contrato CHARACTER VARYING(20) NULL,
	mcades TEXT NULL,
	BloqueioAuto CHARACTER VARYING(3) NULL,
	Ativacao_CL DATE NULL,
	Cancelamento_CL DATE NULL,
	empCGC BIGINT NULL,
	empRaz CHARACTER VARYING(1000) NULL,
	empEnd CHARACTER VARYING(500) NULL,
	empBai CHARACTER VARYING(100) NULL,
	empCid CHARACTER VARYING(100) NULL,
	empUF CHARACTER VARYING(5) NULL,
	empCEP CHARACTER VARYING(20) NULL,
	Documento CHARACTER VARYING(100) NULL,
	Nome CHARACTER VARYING(500) NULL,
	tipo CHARACTER VARYING(100) NULL,
	atv CHARACTER VARYING(500) NULL,
	cel CHARACTER VARYING(20) NULL,
	empCodPai CHARACTER VARYING(20) NULL,
	CobraTxExtra CHARACTER VARYING(5) NULL,
	NomeTipoContrato CHARACTER VARYING(100) NULL,
	VCM NUMERIC NULL,
	DOPERACIONAL NUMERIC NULL,
	DNF NUMERIC NULL,
	DINFRAESTRUTURA NUMERIC NULL,
	CONTROLE_LEGAL NUMERIC NULL,
	MEPROTEJA NUMERIC NULL,
	VOUCHER NUMERIC NULL,
	Tabela CHARACTER VARYING(5) NULL,
	BloqueioManual CHARACTER VARYING(5) NULL,
	CPFCNPJRepresentante BIGINT NULL,
	tipoPessoa CHARACTER VARYING(5) NULL,
	NomeRepresentante CHARACTER VARYING(100) NULL,
	Cargo CHARACTER VARYING(100) NULL,
	empTermoFianca CHARACTER VARYING(5) NULL,
	empNomeFiador CHARACTER VARYING(100) NULL,
	empCPFFiador CHARACTER VARYING(100) NULL
);
